services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  equipment-configurator:
    build:
      context: ./equipment-configurator
    ports:
      - "5001:5001"
    volumes:
      - ./equipment-configurator/cert:/app/cert
    networks:
      - backend
    depends_on:
      - rabbitmq

  async-service:
    build:
      context: ./async-service
    ports:
      - "5002:5002"
    volumes:
      - ./async-service/cert:/app/cert
    networks:
      - backend
    depends_on:
      - rabbitmq
      - equipment-configurator

  worker:
    build:
      context: ./async-service
    command: ["python", "worker.py"]
    volumes:
      - ./async-service/cert:/app/cert
    networks:
      - backend
    depends_on:
      - rabbitmq
      - equipment-configurator

networks:
  backend:
