services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  equipment-configurator:
    build: ./equipment-configurator
    ports:
      - "5001:5001"
    volumes:
      - ./equipment-configurator/cert:/app/cert
    depends_on:
      - rabbitmq

  async-service:
    build: ./async-service
    ports:
      - "5002:5002"
    volumes:
      - ./async-service:/app
    depends_on:
      - rabbitmq
      - equipment-configurator
    environment:
      - PYTHONUNBUFFERED=1

  worker:
    build: ./async-service
    volumes:
      - ./async-service:/app
    depends_on:
      - rabbitmq
      - equipment-configurator
    command: ["python", "worker.py"]
    environment:
      - PYTHONUNBUFFERED=1
